# Generated by Django 5.2.1 on 2025-05-20 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_url', models.URLField(unique=True)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('money_to_pay', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('fine', 'Fine')], max_length=10)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='borrowings.borrowing')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('borrowing'), models.F('type'), name='unique_type_borrowing')],
            },
        ),
    ]
