# Generated by Django 5.2.1 on 2025-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft')], max_length=4)),
                ('inventory', models.PositiveIntegerField()),
                ('daily_fee', models.PositiveIntegerField()),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
            ],
        ),
    ]
